export const veloStatsAbi = [
  {
    constant: true,
    inputs: [
      {
        name: "_limit",
        type: "uint256",
      },
      {
        name: "_offset",
        type: "uint256",
      },
    ],
    name: "all",
    outputs: [
      {
        name: "lp",
        type: "tuple[]",
        components: [
          { type: "address", name: "poolAddress" },
          { type: "string", name: "symbol" },
          { type: "uint256", name: "decimals" },
          { type: "uint256", name: "liquidity" },
          { type: "uint256", name: "type" },
          { type: "uint256", name: "tick" },
          { type: "uint256", name: "sqrt_ratio" },
          { type: "address", name: "token0" },
          { type: "uint256", name: "reserve0" },
          { type: "uint256", name: "staked0" },
          { type: "address", name: "token1" },
          { type: "uint256", name: "reserve1" },
          { type: "uint256", name: "staked1" },
          { type: "address", name: "gauge" },
          { type: "uint256", name: "gauge_liquidity" },
          { type: "bool", name: "gauge_alive" },
          { type: "address", name: "fee" },
          { type: "address", name: "bribe" },
          { type: "address", name: "factory" },
          { type: "uint256", name: "emissions" },
          { type: "address", name: "emissions_token" },
          { type: "uint256", name: "pool_fee" },
          { type: "uint256", name: "unstaked_fee" },
          { type: "uint256", name: "token0_fees" },
          { type: "uint256", name: "token1_fees" },
          { type: "address", name: "nfpm" },
          { type: "address", name: "alm" },
        ],
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;
