/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VaultsImport } from './routes/vaults'
import { Route as TransmutersImport } from './routes/transmuters'

// Create Virtual Routes

const UtilitiesLazyImport = createFileRoute('/utilities')()
const SentinelLazyImport = createFileRoute('/sentinel')()
const GovernanceLazyImport = createFileRoute('/governance')()
const FarmsLazyImport = createFileRoute('/farms')()
const DebugLazyImport = createFileRoute('/debug')()
const BridgeLazyImport = createFileRoute('/bridge')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UtilitiesLazyRoute = UtilitiesLazyImport.update({
  path: '/utilities',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/utilities.lazy').then((d) => d.Route))

const SentinelLazyRoute = SentinelLazyImport.update({
  path: '/sentinel',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sentinel.lazy').then((d) => d.Route))

const GovernanceLazyRoute = GovernanceLazyImport.update({
  path: '/governance',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/governance.lazy').then((d) => d.Route))

const FarmsLazyRoute = FarmsLazyImport.update({
  path: '/farms',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/farms.lazy').then((d) => d.Route))

const DebugLazyRoute = DebugLazyImport.update({
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/debug.lazy').then((d) => d.Route))

const BridgeLazyRoute = BridgeLazyImport.update({
  path: '/bridge',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bridge.lazy').then((d) => d.Route))

const VaultsRoute = VaultsImport.update({
  path: '/vaults',
  getParentRoute: () => rootRoute,
} as any)

const TransmutersRoute = TransmutersImport.update({
  path: '/transmuters',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/transmuters': {
      id: '/transmuters'
      path: '/transmuters'
      fullPath: '/transmuters'
      preLoaderRoute: typeof TransmutersImport
      parentRoute: typeof rootRoute
    }
    '/vaults': {
      id: '/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsImport
      parentRoute: typeof rootRoute
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeLazyImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugLazyImport
      parentRoute: typeof rootRoute
    }
    '/farms': {
      id: '/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof FarmsLazyImport
      parentRoute: typeof rootRoute
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceLazyImport
      parentRoute: typeof rootRoute
    }
    '/sentinel': {
      id: '/sentinel'
      path: '/sentinel'
      fullPath: '/sentinel'
      preLoaderRoute: typeof SentinelLazyImport
      parentRoute: typeof rootRoute
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/transmuters': typeof TransmutersRoute
  '/vaults': typeof VaultsRoute
  '/bridge': typeof BridgeLazyRoute
  '/debug': typeof DebugLazyRoute
  '/farms': typeof FarmsLazyRoute
  '/governance': typeof GovernanceLazyRoute
  '/sentinel': typeof SentinelLazyRoute
  '/utilities': typeof UtilitiesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/transmuters': typeof TransmutersRoute
  '/vaults': typeof VaultsRoute
  '/bridge': typeof BridgeLazyRoute
  '/debug': typeof DebugLazyRoute
  '/farms': typeof FarmsLazyRoute
  '/governance': typeof GovernanceLazyRoute
  '/sentinel': typeof SentinelLazyRoute
  '/utilities': typeof UtilitiesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/transmuters': typeof TransmutersRoute
  '/vaults': typeof VaultsRoute
  '/bridge': typeof BridgeLazyRoute
  '/debug': typeof DebugLazyRoute
  '/farms': typeof FarmsLazyRoute
  '/governance': typeof GovernanceLazyRoute
  '/sentinel': typeof SentinelLazyRoute
  '/utilities': typeof UtilitiesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/transmuters'
    | '/vaults'
    | '/bridge'
    | '/debug'
    | '/farms'
    | '/governance'
    | '/sentinel'
    | '/utilities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/transmuters'
    | '/vaults'
    | '/bridge'
    | '/debug'
    | '/farms'
    | '/governance'
    | '/sentinel'
    | '/utilities'
  id:
    | '__root__'
    | '/'
    | '/transmuters'
    | '/vaults'
    | '/bridge'
    | '/debug'
    | '/farms'
    | '/governance'
    | '/sentinel'
    | '/utilities'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TransmutersRoute: typeof TransmutersRoute
  VaultsRoute: typeof VaultsRoute
  BridgeLazyRoute: typeof BridgeLazyRoute
  DebugLazyRoute: typeof DebugLazyRoute
  FarmsLazyRoute: typeof FarmsLazyRoute
  GovernanceLazyRoute: typeof GovernanceLazyRoute
  SentinelLazyRoute: typeof SentinelLazyRoute
  UtilitiesLazyRoute: typeof UtilitiesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TransmutersRoute: TransmutersRoute,
  VaultsRoute: VaultsRoute,
  BridgeLazyRoute: BridgeLazyRoute,
  DebugLazyRoute: DebugLazyRoute,
  FarmsLazyRoute: FarmsLazyRoute,
  GovernanceLazyRoute: GovernanceLazyRoute,
  SentinelLazyRoute: SentinelLazyRoute,
  UtilitiesLazyRoute: UtilitiesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/transmuters",
        "/vaults",
        "/bridge",
        "/debug",
        "/farms",
        "/governance",
        "/sentinel",
        "/utilities"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/transmuters": {
      "filePath": "transmuters.tsx"
    },
    "/vaults": {
      "filePath": "vaults.tsx"
    },
    "/bridge": {
      "filePath": "bridge.lazy.tsx"
    },
    "/debug": {
      "filePath": "debug.lazy.tsx"
    },
    "/farms": {
      "filePath": "farms.lazy.tsx"
    },
    "/governance": {
      "filePath": "governance.lazy.tsx"
    },
    "/sentinel": {
      "filePath": "sentinel.lazy.tsx"
    },
    "/utilities": {
      "filePath": "utilities.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
